services:
  database:
    build: database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  python-service:
    build: python-service
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=app
      - DATABASE_USER=root
      - DATABASE_PASSWORD=toor
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"

  node-service:
    build:
      context: .
      args:
        - SERVICE_HOST=http://python-service:5000
    depends_on:
      - python-service
    ports:
      - "80:3000"